reverence/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:item_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:item_id>/', views.cart_remove, name='cart_remove'),
    path('update/<int:item_id>/', views.CartUpdateView.as_view(), name="cart_update"),
]

reverence/reverence/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('main.urls', namespace='main'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

reverence/users/urls.py
from django.urls import path
from . import views


app_name = "users"

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
]

reverence/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    middle_name = models.CharField(max_length=30, blank=True)
    city = models.CharField(max_length=30, blank=True)
    street = models.CharField(max_length=50, blank=True)
    house_number = models.CharField(max_length=10, blank=True)
    apartment_number = models.CharField(max_length=10, blank=True)
    post_code = models.CharField(max_length=10, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.email

reverence/users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from .models import User


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        if password1 and len(password1) < 8:
            self.add_error('password1', 'Mimimum 8 characters.')
        return password1

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        return password2


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'first_name', 'last_name', 'middle_name', 'city',
            'house_number', 'apartment_number', 'post_code',
        ]

reverence/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import UserRegistrationForm, UserLoginForm, UserProfileForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
# from orders.models import Order


def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('users:login')
    else:
        form = UserRegistrationForm()

    return render(request, 'users/register.html', {'form': form})


def user_login(request):
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                return redirect('main:catalog')
    else:
        form = UserLoginForm()

    return render(request, 'users/login.html', {'form': form})


@login_required(login_url='/users/login')
def user_logout(request):
    logout(request)
    return redirect('uders:login')

reverence/users/templates/users/login.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Reverence Interlude - Login{% endblock title %}

{% block content %}
    <div class="login-container d-flex justify-content-center">
        <div class="login d-flex flex-column">
            <h3 class="text-center mb-5">Login</h3>
            <form metho="post" class="loginform">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="loginbtns d-flex justify-content-between align-items-center">
                    <button type="submit" class="default-btn mt-2">Login</button>
                    <a href="{% url "users:register" %}" class="create-account-btn">No account</a>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

reverence/users/templates/users/register.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Reverence Interlude - Registration{% endblock title %}

{% block content %}
    <div class="login-container d-flex justify-content-center">
        <div class="login d-flex flex-column">
            <h3 class="text-center mb-3">Registration</h3>
            <form method="post" class="loginform">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group mb-3 d-flex flex-column">
                        {{ field.label_tag }}
                        {{ field }}
                        {% if field.errors %}
                            <div class="error">{{ field.errors }}</div>
                        {% endif %}
                    </div>
                {% endfor %}
                <div class="loginbtns d-flex justify-content-between align-items-center">
                    <button class="default-btn nt-3">Register</button>
                    <a href="{% url "users:login" %}" class="create-account-btn">Have account?</a>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}